### ISSUE TITLE
Mark external links with an icon

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/handbook#2123]
## Context

Internal and external links look the same now.

<img src="https://user-images.githubusercontent.com/2552265/152179486-fff30384-4bc4-4faa-ad69-bf3324d1821a.png" alt="Internal vs external" width=300px />

## Proposal

I'd find it helpful if external links were marked with an icon like on Wikipedia and some other sites.
It looks like a matter of a CSS tweak, and I'm happy to contribute.

## More info

Two solution ideas from @felixfbecker:

```css
a[href^="https://"]::after {
  content: '↗';
}
```
This would be just a simple arrow but nice in that it will automatically adapt the color. Might actually work well in our minimal design. (font size, margin etc can be tweaked)
Or alternatively like Wikipedia with an SVG as a background image, placed on the right side using some padding:
```css
a[href^="https://"] {
  background-image: url(external-link-icon.svg);
  background-position: center right;
  background-repeat: no-repeat;
  padding-right: 1em;
}
```
(note that in this case the color of the SVG must be hardcoded to our link color and not adapt dynamically to the :visited / :hover / :active link color)

@jeanduplessis: "Feel free to implement and reach out to #content-platform team if you need help."

@quinnkeast: "We do this in the Sourcegraph product itself. I think it’s a good pattern to adopt!"

![image](https://user-images.githubusercontent.com/2552265/152181001-a708affe-174c-41a1-b241-fbcac2fb2486.png)
